### ISSUE TITLE
suggestions wrt. JWK "alg" and "use" fields

### ISSUE THREAD

**Issue by panva** [twiss/webcrypto-secure-curves#2]
Since Ed* keys can only be used for signatures (and have one dedicated JWS "alg" identifier) and X* can only be used for ECDH (meaning not the WebCrypto algorithm identifier here) the following operation steps should be added. The `alg` ones I think for sure, the `use` ones I'll leave to a discussion.

---

**Ed25519 JWK importKey operation**

Add a step

> If the `alg` field of jwk is present and not "EdDSA", then throw a DataError.

---

**Ed448 JWK importKey operation**

Add a step

> If the `alg` field of jwk is present and not "EdDSA", then throw a DataError.

---

**Ed25519 JWK exportKey operation**

Add steps

> Set the `alg` attribute of jwk to "EdDSA".
> Set the `use` attribute of jwk to "sig".

---

**Ed448 JWK exportKey operation**

Add steps

> Set the `alg` attribute of jwk to "EdDSA".
> Set the `use` attribute of jwk to "sig".

---

**X25519 JWK exportKey operation**

Add a step

> Set the `use` attribute of jwk to "enc".

---

**X448 JWK exportKey operation**

Add a step

> Set the `use` attribute of jwk to "enc".

**Comment by twiss** [comment]
Yeah, I definitely agree with should add the `alg` field, thanks for catching that.

The `use` attribute I don't think we should set, as the Web Crypto spec currently doesn't do so either for any of the algorithms (while it does check them on import; I assume the intention was to have the `key_ops` field fulfill the same role for exported keys).

**Comment by panva** [comment]
I'll remove the use commits from my PR

**Comment by panva** [comment]
#3 updated.
